/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Sathisha
 */
import db.database;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

public class EmployeeDashboard extends javax.swing.JFrame {
    private JButton bestSellingButton;
    private JButton productPerformanceButton;
    private JButton customerAnalysisButton;
    private JButton branchPerformanceButton;
    private JButton salesAnalysisButton;
    private JPanel mainPanel;
    /**
     * Creates new form EmployeeDashboard
     */
    public EmployeeDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnbranchPerformanceButton = new javax.swing.JButton();
        btnbestSellingButton = new javax.swing.JButton();
        btnsalesAnalysisButton = new javax.swing.JButton();
        btncustomerAnalysisButton = new javax.swing.JButton();
        btnproductPerformanceButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnsalesAnalysisButton1 = new javax.swing.JButton();
        btnsalesAnalysisButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnsalesAnalysisButton3 = new javax.swing.JButton();
        txtUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Employee Dashboard");

        btnbranchPerformanceButton.setBackground(new java.awt.Color(102, 255, 255));
        btnbranchPerformanceButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnbranchPerformanceButton.setText("Branch Performance");
        btnbranchPerformanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbranchPerformanceButtonActionPerformed(evt);
            }
        });

        btnbestSellingButton.setBackground(new java.awt.Color(102, 255, 255));
        btnbestSellingButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnbestSellingButton.setText("Best Selling Products");
        btnbestSellingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbestSellingButtonActionPerformed(evt);
            }
        });

        btnsalesAnalysisButton.setBackground(new java.awt.Color(102, 255, 255));
        btnsalesAnalysisButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsalesAnalysisButton.setText("Daily Sales Analysis");
        btnsalesAnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalesAnalysisButtonActionPerformed(evt);
            }
        });

        btncustomerAnalysisButton.setBackground(new java.awt.Color(102, 255, 255));
        btncustomerAnalysisButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btncustomerAnalysisButton.setText("Customer Analysis");
        btncustomerAnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomerAnalysisButtonActionPerformed(evt);
            }
        });

        btnproductPerformanceButton.setBackground(new java.awt.Color(102, 255, 255));
        btnproductPerformanceButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnproductPerformanceButton.setText("Product Performance");
        btnproductPerformanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductPerformanceButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnsalesAnalysisButton1.setBackground(new java.awt.Color(102, 255, 255));
        btnsalesAnalysisButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsalesAnalysisButton1.setText("Annual Sales Analysis");
        btnsalesAnalysisButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalesAnalysisButton1ActionPerformed(evt);
            }
        });

        btnsalesAnalysisButton2.setBackground(new java.awt.Color(102, 255, 255));
        btnsalesAnalysisButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsalesAnalysisButton2.setText("Monthly Sales Analysis");
        btnsalesAnalysisButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalesAnalysisButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Sales Analysis");

        btnsalesAnalysisButton3.setBackground(new java.awt.Color(102, 255, 255));
        btnsalesAnalysisButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsalesAnalysisButton3.setText("Change Password");
        btnsalesAnalysisButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalesAnalysisButton3ActionPerformed(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbranchPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnsalesAnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(btnsalesAnalysisButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsalesAnalysisButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(btnbestSellingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(btnproductPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsalesAnalysisButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncustomerAnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(580, 580, 580))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnproductPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncustomerAnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbestSellingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbranchPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalesAnalysisButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalesAnalysisButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalesAnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalesAnalysisButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbranchPerformanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbranchPerformanceButtonActionPerformed
        // TODO add your handling code here:
         /*String query = "SELECT Region, SUM(TotalPrice) AS TotalSales FROM Sales GROUP BY Region";
                try (Connection conn = database.getConnection();
                     PreparedStatement stmt = conn.prepareStatement(query);
                     ResultSet rs = stmt.executeQuery()) {
                    StringBuilder result = new StringBuilder("Branch Performance:\n");
                    while (rs.next()) {
                        result.append(rs.getString("Region")).append(": ").append(rs.getDouble("TotalSales")).append("\n");
                    }
                    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
                } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                }*/
         branchperformance brpf = new branchperformance();
            brpf.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_btnbranchPerformanceButtonActionPerformed

    private void btnbestSellingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbestSellingButtonActionPerformed
        // TODO add your handling code here:
        /* String query = "SELECT ProductName, SUM(Quantity) AS TotalQuantity FROM Sales GROUP BY ProductName ORDER BY TotalQuantity DESC";
                try (Connection conn = database.getConnection();
                     PreparedStatement stmt = conn.prepareStatement(query);
                     ResultSet rs = stmt.executeQuery()) {
                    StringBuilder result = new StringBuilder("Best Selling Products:\n");
                    while (rs.next()) {
                        result.append(rs.getString("ProductName")).append(": ").append(rs.getInt("TotalQuantity")).append("\n");
                    }
                    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
                } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                }*/
        bestselligproducrs bsp = new bestselligproducrs();
            bsp.setVisible(true);
            this.dispose();
       
    }//GEN-LAST:event_btnbestSellingButtonActionPerformed

    private void btnsalesAnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalesAnalysisButtonActionPerformed
        // TODO add your handling code here:
       
        /*String query = "SELECT Date, SUM(TotalPrice) AS DailySales FROM Sales GROUP BY Date";
                try (Connection conn = database.getConnection();
                     PreparedStatement stmt = conn.prepareStatement(query);
                     ResultSet rs = stmt.executeQuery()) {
                    StringBuilder result = new StringBuilder("Sales Analysis (Daily):\n");
                    while (rs.next()) {
                        result.append(rs.getDate("Date")).append(": ").append(rs.getDouble("DailySales")).append("\n");
                    }
                    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
                } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                }*/
         SalesAnalysisDaily sad = new SalesAnalysisDaily();
            sad.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_btnsalesAnalysisButtonActionPerformed

    private void btncustomerAnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerAnalysisButtonActionPerformed
        // TODO add your handling code here:
        /* String query = "SELECT CustomerID, SUM(TotalPrice) AS TotalSpent FROM Sales GROUP BY CustomerID";

try (Connection conn = database.getConnection();
     PreparedStatement stmt = conn.prepareStatement(query);
     ResultSet rs = stmt.executeQuery()) {

    StringBuilder result = new StringBuilder("Customer Analysis:\n");
    while (rs.next()) {
        int customerId = rs.getInt("CustomerID");
        double totalSpent = rs.getDouble("TotalSpent");

        // Append customer analysis details
        result.append("Customer ").append(customerId)
              .append(": LKR").append(String.format("%.2f", totalSpent)).append("\n");
    }

    // Display the result in a dialog box
    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString(), "Customer Analysis", JOptionPane.INFORMATION_MESSAGE);
} catch (Exception e) {
    // Provide a meaningful error message
    JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}*/
         CustomerAnalysis ca = new CustomerAnalysis();
            ca.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btncustomerAnalysisButtonActionPerformed

    private void btnproductPerformanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductPerformanceButtonActionPerformed
        // TODO add your handling code here:
      /* String query = "SELECT ProductName, SUM(Quantity) AS TotalQuantity " +
               "FROM Sales " +
               "GROUP BY ProductName";

try (Connection conn = database.getConnection();
     PreparedStatement stmt = conn.prepareStatement(query);
     ResultSet rs = stmt.executeQuery()) {

    StringBuilder result = new StringBuilder("Product Performance (Total):\n");
    while (rs.next()) {
        String productName = rs.getString("ProductName");
        int totalQuantity = rs.getInt("TotalQuantity");

        // Append the product performance details
        result.append("Product: ").append(productName)
              .append(" | Total Quantity Sold: ").append(totalQuantity)
              .append("\n");
    }

    // Display the result in a dialog box
    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
} catch (Exception e) {
    // Provide a meaningful error message
    JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}*/
       ProductPerformance ppf = new ProductPerformance();
            ppf.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnproductPerformanceButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsalesAnalysisButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalesAnalysisButton1ActionPerformed
        // TODO add your handling code here:
       /* String query = "SELECT YEAR(Date) AS SalesYear, SUM(TotalPrice) AS AnnualSales " +
               "FROM Sales " +
               "GROUP BY YEAR(Date)";

try (Connection conn = database.getConnection();
     PreparedStatement stmt = conn.prepareStatement(query);
     ResultSet rs = stmt.executeQuery()) {

    StringBuilder result = new StringBuilder("Sales Analysis (Annual):\n");
    while (rs.next()) {
        int year = rs.getInt("SalesYear");
        double annualSales = rs.getDouble("AnnualSales");

        // Append the year and annual sales to the result
        result.append(year).append(": ").append(annualSales).append("\n");
    }

    // Display the result in a dialog box
    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.toString());
}*/
        SalesAnalysisAnnual saa = new SalesAnalysisAnnual();
            saa.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnsalesAnalysisButton1ActionPerformed

    private void btnsalesAnalysisButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalesAnalysisButton2ActionPerformed
        // TODO add your handling code here:
       /* String query = "SELECT YEAR(Date) AS SalesYear, MONTH(Date) AS SalesMonth, SUM(TotalPrice) AS MonthlySales " +
               "FROM Sales " +
               "GROUP BY YEAR(Date), MONTH(Date)";

try (Connection conn = database.getConnection();
     PreparedStatement stmt = conn.prepareStatement(query);
     ResultSet rs = stmt.executeQuery()) {

    StringBuilder result = new StringBuilder("Sales Analysis (Monthly):\n");
    while (rs.next()) {
        int year = rs.getInt("SalesYear");
        int month = rs.getInt("SalesMonth");
        double monthlySales = rs.getDouble("MonthlySales");

        // Format the month and year for display
        String monthYear = String.format("%04d-%02d", year, month);
        result.append(monthYear).append(": ").append(monthlySales).append("\n");
    }

    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.toString());
}*/
        SalesAnalysisMonthly sam = new SalesAnalysisMonthly();
            sam.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnsalesAnalysisButton2ActionPerformed

    private void btnsalesAnalysisButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalesAnalysisButton3ActionPerformed
        // TODO add your handling code here:
        ChangePasswordemployee cps = new ChangePasswordemployee();
        cps.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnsalesAnalysisButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbestSellingButton;
    private javax.swing.JButton btnbranchPerformanceButton;
    private javax.swing.JButton btncustomerAnalysisButton;
    private javax.swing.JButton btnproductPerformanceButton;
    private javax.swing.JButton btnsalesAnalysisButton;
    private javax.swing.JButton btnsalesAnalysisButton1;
    private javax.swing.JButton btnsalesAnalysisButton2;
    private javax.swing.JButton btnsalesAnalysisButton3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
