/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Sathisha
 */
import db.database;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

public class EmployeeDashboard extends javax.swing.JFrame {
    private JButton bestSellingButton;
    private JButton productPerformanceButton;
    private JButton customerAnalysisButton;
    private JButton branchPerformanceButton;
    private JButton salesAnalysisButton;
    private JPanel mainPanel;
    /**
     * Creates new form EmployeeDashboard
     */
    public EmployeeDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnbranchPerformanceButton = new javax.swing.JButton();
        btnbestSellingButton = new javax.swing.JButton();
        btnsalesAnalysisButton = new javax.swing.JButton();
        btncustomerAnalysisButton = new javax.swing.JButton();
        btnproductPerformanceButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnsalesAnalysisButton1 = new javax.swing.JButton();
        btnsalesAnalysisButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Employee Dashboard");

        btnbranchPerformanceButton.setBackground(new java.awt.Color(102, 255, 255));
        btnbranchPerformanceButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnbranchPerformanceButton.setText("Branch Performance");
        btnbranchPerformanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbranchPerformanceButtonActionPerformed(evt);
            }
        });

        btnbestSellingButton.setBackground(new java.awt.Color(102, 255, 255));
        btnbestSellingButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnbestSellingButton.setText("Best Selling Products");
        btnbestSellingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbestSellingButtonActionPerformed(evt);
            }
        });

        btnsalesAnalysisButton.setBackground(new java.awt.Color(102, 255, 255));
        btnsalesAnalysisButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsalesAnalysisButton.setText("Daily Sales Analysis");
        btnsalesAnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalesAnalysisButtonActionPerformed(evt);
            }
        });

        btncustomerAnalysisButton.setBackground(new java.awt.Color(102, 255, 255));
        btncustomerAnalysisButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btncustomerAnalysisButton.setText("Customer Analysis");
        btncustomerAnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomerAnalysisButtonActionPerformed(evt);
            }
        });

        btnproductPerformanceButton.setBackground(new java.awt.Color(102, 255, 255));
        btnproductPerformanceButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnproductPerformanceButton.setText("Product Performance");
        btnproductPerformanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductPerformanceButtonActionPerformed(evt);
            }
        });

        jButton1.setText("logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnsalesAnalysisButton1.setBackground(new java.awt.Color(102, 255, 255));
        btnsalesAnalysisButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsalesAnalysisButton1.setText("Annual Sales Analysis");
        btnsalesAnalysisButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalesAnalysisButton1ActionPerformed(evt);
            }
        });

        btnsalesAnalysisButton2.setBackground(new java.awt.Color(102, 255, 255));
        btnsalesAnalysisButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnsalesAnalysisButton2.setText("Monthly Sales Analysis");
        btnsalesAnalysisButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalesAnalysisButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Sales Analysis");

        jButton6.setBackground(new java.awt.Color(102, 153, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setText("load csv file");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(647, 647, 647)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnbestSellingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsalesAnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(115, 115, 115)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnproductPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsalesAnalysisButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btncustomerAnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsalesAnalysisButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnbranchPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnproductPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncustomerAnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbestSellingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnbranchPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalesAnalysisButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalesAnalysisButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalesAnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbranchPerformanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbranchPerformanceButtonActionPerformed
        // TODO add your handling code here:
         /*String query = "SELECT Region, SUM(TotalPrice) AS TotalSales FROM Sales GROUP BY Region";
                try (Connection conn = database.getConnection();
                     PreparedStatement stmt = conn.prepareStatement(query);
                     ResultSet rs = stmt.executeQuery()) {
                    StringBuilder result = new StringBuilder("Branch Performance:\n");
                    while (rs.next()) {
                        result.append(rs.getString("Region")).append(": ").append(rs.getDouble("TotalSales")).append("\n");
                    }
                    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
                } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                }*/
         branchperformance brpf = new branchperformance();
            brpf.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_btnbranchPerformanceButtonActionPerformed

    private void btnbestSellingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbestSellingButtonActionPerformed
        // TODO add your handling code here:
        /* String query = "SELECT ProductName, SUM(Quantity) AS TotalQuantity FROM Sales GROUP BY ProductName ORDER BY TotalQuantity DESC";
                try (Connection conn = database.getConnection();
                     PreparedStatement stmt = conn.prepareStatement(query);
                     ResultSet rs = stmt.executeQuery()) {
                    StringBuilder result = new StringBuilder("Best Selling Products:\n");
                    while (rs.next()) {
                        result.append(rs.getString("ProductName")).append(": ").append(rs.getInt("TotalQuantity")).append("\n");
                    }
                    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
                } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                }*/
        bestselligproducrs bsp = new bestselligproducrs();
            bsp.setVisible(true);
            this.dispose();
       
    }//GEN-LAST:event_btnbestSellingButtonActionPerformed

    private void btnsalesAnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalesAnalysisButtonActionPerformed
        // TODO add your handling code here:
       
        /*String query = "SELECT Date, SUM(TotalPrice) AS DailySales FROM Sales GROUP BY Date";
                try (Connection conn = database.getConnection();
                     PreparedStatement stmt = conn.prepareStatement(query);
                     ResultSet rs = stmt.executeQuery()) {
                    StringBuilder result = new StringBuilder("Sales Analysis (Daily):\n");
                    while (rs.next()) {
                        result.append(rs.getDate("Date")).append(": ").append(rs.getDouble("DailySales")).append("\n");
                    }
                    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
                } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                }*/
         SalesAnalysisDaily sad = new SalesAnalysisDaily();
            sad.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_btnsalesAnalysisButtonActionPerformed

    private void btncustomerAnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerAnalysisButtonActionPerformed
        // TODO add your handling code here:
        /* String query = "SELECT CustomerID, SUM(TotalPrice) AS TotalSpent FROM Sales GROUP BY CustomerID";

try (Connection conn = database.getConnection();
     PreparedStatement stmt = conn.prepareStatement(query);
     ResultSet rs = stmt.executeQuery()) {

    StringBuilder result = new StringBuilder("Customer Analysis:\n");
    while (rs.next()) {
        int customerId = rs.getInt("CustomerID");
        double totalSpent = rs.getDouble("TotalSpent");

        // Append customer analysis details
        result.append("Customer ").append(customerId)
              .append(": LKR").append(String.format("%.2f", totalSpent)).append("\n");
    }

    // Display the result in a dialog box
    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString(), "Customer Analysis", JOptionPane.INFORMATION_MESSAGE);
} catch (Exception e) {
    // Provide a meaningful error message
    JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}*/
         CustomerAnalysis ca = new CustomerAnalysis();
            ca.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btncustomerAnalysisButtonActionPerformed

    private void btnproductPerformanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductPerformanceButtonActionPerformed
        // TODO add your handling code here:
      /* String query = "SELECT ProductName, SUM(Quantity) AS TotalQuantity " +
               "FROM Sales " +
               "GROUP BY ProductName";

try (Connection conn = database.getConnection();
     PreparedStatement stmt = conn.prepareStatement(query);
     ResultSet rs = stmt.executeQuery()) {

    StringBuilder result = new StringBuilder("Product Performance (Total):\n");
    while (rs.next()) {
        String productName = rs.getString("ProductName");
        int totalQuantity = rs.getInt("TotalQuantity");

        // Append the product performance details
        result.append("Product: ").append(productName)
              .append(" | Total Quantity Sold: ").append(totalQuantity)
              .append("\n");
    }

    // Display the result in a dialog box
    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
} catch (Exception e) {
    // Provide a meaningful error message
    JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}*/
       ProductPerformance ppf = new ProductPerformance();
            ppf.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnproductPerformanceButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsalesAnalysisButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalesAnalysisButton1ActionPerformed
        // TODO add your handling code here:
       /* String query = "SELECT YEAR(Date) AS SalesYear, SUM(TotalPrice) AS AnnualSales " +
               "FROM Sales " +
               "GROUP BY YEAR(Date)";

try (Connection conn = database.getConnection();
     PreparedStatement stmt = conn.prepareStatement(query);
     ResultSet rs = stmt.executeQuery()) {

    StringBuilder result = new StringBuilder("Sales Analysis (Annual):\n");
    while (rs.next()) {
        int year = rs.getInt("SalesYear");
        double annualSales = rs.getDouble("AnnualSales");

        // Append the year and annual sales to the result
        result.append(year).append(": ").append(annualSales).append("\n");
    }

    // Display the result in a dialog box
    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.toString());
}*/
        SalesAnalysisAnnual saa = new SalesAnalysisAnnual();
            saa.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnsalesAnalysisButton1ActionPerformed

    private void btnsalesAnalysisButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalesAnalysisButton2ActionPerformed
        // TODO add your handling code here:
       /* String query = "SELECT YEAR(Date) AS SalesYear, MONTH(Date) AS SalesMonth, SUM(TotalPrice) AS MonthlySales " +
               "FROM Sales " +
               "GROUP BY YEAR(Date), MONTH(Date)";

try (Connection conn = database.getConnection();
     PreparedStatement stmt = conn.prepareStatement(query);
     ResultSet rs = stmt.executeQuery()) {

    StringBuilder result = new StringBuilder("Sales Analysis (Monthly):\n");
    while (rs.next()) {
        int year = rs.getInt("SalesYear");
        int month = rs.getInt("SalesMonth");
        double monthlySales = rs.getDouble("MonthlySales");

        // Format the month and year for display
        String monthYear = String.format("%04d-%02d", year, month);
        result.append(monthYear).append(": ").append(monthlySales).append("\n");
    }

    JOptionPane.showMessageDialog(EmployeeDashboard.this, result.toString());
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e.toString());
}*/
        SalesAnalysisMonthly sam = new SalesAnalysisMonthly();
            sam.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnsalesAnalysisButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            // Open a file chooser dialog to select a CSV file
            JFileChooser jfilech = new JFileChooser();
            jfilech.setDialogTitle("Select a CSV file");
            int userSelected = jfilech.showOpenDialog(null);

            if (userSelected == JFileChooser.APPROVE_OPTION) {
                File filepath = jfilech.getSelectedFile();
                String file = filepath.getAbsolutePath();

                try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                    String line;
                    boolean firstLine = true;

                    // Read the CSV file line by line
                    while ((line = br.readLine()) != null) {
                        if (firstLine) {
                            firstLine = false; // Skip the header line
                            continue;
                        }

                        // Split the line by commas
                        String[] data = line.split(",");

                        // Format the date
                        SimpleDateFormat originalFormat = new SimpleDateFormat("M/d/yyyy");
                        SimpleDateFormat targetFormat = new SimpleDateFormat("yyyy-MM-dd");
                        java.util.Date date = originalFormat.parse(data[6]); // Parse the date
                        String formattedDate = targetFormat.format(date); // Format the date

                        // Insert data into the database
                        try (Connection conn = database.getConnection()) {
                            String query = "INSERT INTO Sales (TransactionID, CustomerID, ProductID, ProductName, Quantity, PriceperUnit, Date, TotalPrice, Region) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                            PreparedStatement stmt = conn.prepareStatement(query);

                            stmt.setInt(1, Integer.parseInt(data[0])); // TransactionID
                            stmt.setInt(2, Integer.parseInt(data[1])); // CustomerID
                            stmt.setInt(3, Integer.parseInt(data[2])); // ProductID
                            stmt.setString(4, data[3]); // ProductName
                            stmt.setInt(5, Integer.parseInt(data[4])); // Quantity
                            stmt.setDouble(6, Double.parseDouble(data[5])); // PricePerUnit
                            stmt.setString(7, formattedDate); // Formatted Date
                            stmt.setDouble(8, Double.parseDouble(data[7])); // TotalPrice
                            stmt.setString(9, data[8]); // Region

                            stmt.executeUpdate(); // Execute the query
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
                        }
                    }

                    JOptionPane.showMessageDialog(null, "CSV data loaded successfully!");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "File reading error: " + e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "No file selected!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbestSellingButton;
    private javax.swing.JButton btnbranchPerformanceButton;
    private javax.swing.JButton btncustomerAnalysisButton;
    private javax.swing.JButton btnproductPerformanceButton;
    private javax.swing.JButton btnsalesAnalysisButton;
    private javax.swing.JButton btnsalesAnalysisButton1;
    private javax.swing.JButton btnsalesAnalysisButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
